### ISSUE TITLE
General UI issue logic

### ISSUE THREAD

**Issue by GerardClotet** [pink-king/Final-Fantasy-Dawn-of-Ivalice#52]
This isn't a regular issue, its a guide to general logic improvement until the vertical slice.
**IT'S OPEN TO UPDATES AND DELETES**

* The button logic must be disable when the player doesn't has any chance to use it. The dologic()sound shows us that the logic is enable when it shouldn't.

* Once the invetory is opened the description remains in screen even though the invetory is closed
* The equipable loot shouldn't be picked by walking over it, only with scope.

* If pause menu is opened, the invetory can't be opened or if its opened it should be fixed that plays the time again, being inside the pause menu.

**Comment by thedoctormarc** [comment]
Point number 2 fixed, point number 3 is not UI related.

Number 4 has already been debated in the UI department, we will work on it
