### ISSUE TITLE
Crash at HealthBar.cpp  in cleanUp function when exit game

### ISSUE THREAD

**Issue by GerardClotet** [pink-king/Final-Fantasy-Dawn-of-Ivalice#66]
![image](https://user-images.githubusercontent.com/36155703/57884360-b60f6d00-7828-11e9-8e39-13349a612277.png)

When the player kills an enemy and shuts down the application crashes while quitting the game.

May be related that the exit aplication is trying to delete a Healthbar element that's has already been deleted with the enemy dead

Frequency: Medium

**Comment by Sebi-Lopez** [comment]
It crashes even when you don't kill anyone. 
To me, it happened many times exactly at the moment when the camera gets in the position with the player and you close.
